/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VctRibeiraoSerieARouteImport } from './routes/vct-ribeirao/serie-a'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VctRibeiraoSerieARoute = VctRibeiraoSerieARouteImport.update({
  id: '/vct-ribeirao/serie-a',
  path: '/vct-ribeirao/serie-a',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vct-ribeirao/serie-a': typeof VctRibeiraoSerieARoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vct-ribeirao/serie-a': typeof VctRibeiraoSerieARoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vct-ribeirao/serie-a': typeof VctRibeiraoSerieARoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vct-ribeirao/serie-a'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vct-ribeirao/serie-a'
  id: '__root__' | '/' | '/vct-ribeirao/serie-a'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VctRibeiraoSerieARoute: typeof VctRibeiraoSerieARoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vct-ribeirao/serie-a': {
      id: '/vct-ribeirao/serie-a'
      path: '/vct-ribeirao/serie-a'
      fullPath: '/vct-ribeirao/serie-a'
      preLoaderRoute: typeof VctRibeiraoSerieARouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VctRibeiraoSerieARoute: VctRibeiraoSerieARoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
